### ISSUE TITLE
MS Office 2016 colors

### ISSUE THREAD

**Issue by Andreas-Kainz** [noelma/office-color#1]
Hi

as MSO change there color scheme 2016 (or earlier) are you interested into make an color scheme for the 2016 defaults?

**Comment by noelma** [comment]
Hello,
You mean a color scheme like this?
https://docs.microsoft.com/fr-fr/office/dev/add-ins/images/office15-app-color-palette.png

**Comment by Andreas-Kainz** [comment]
Yes the new one.

**Comment by Andreas-Kainz** [comment]
here are the colors
https://evoluteur.github.io/colorpicker/index.html

do you think it's usefull to add two colors to the color paletts? cause MSO has 10 columns and LO 12?

**Comment by noelma** [comment]
It's because LO chose 12 colors that I wanted to create a 10 colors pallette.
12 colors is good if you follow the wheel color. But it's not easy for standard users.

What worries me more than the 12 colors is if the MSO colors are not free.

**Comment by noelma** [comment]
After doing some research, I regret that I can not fulfill this request. What you are asking for is a problem of appropriating a color. There is a risk that Microsoft can turn against LibreOffice or me.
